import { useEffect, useMemo, useState } from 'react'
import { Link, NavLink, Outlet, Route, Routes, useNavigate, useParams } from 'react-router-dom'
import { addComment, claimStage, completeStage, markAllNotificationsRead, markNotificationRead, releaseStage, reviewChapter } from './lib/production'
import { supabase } from './lib/supabase'
import { stageLabel, stageRole } from './workflow'
import type { Chapter, ChapterStage, Role, StaffMember, Stage } from './types'

export type PanelProps = { member: StaffMember; chapters: Chapter[]; notifications: number; toast: string; refresh: () => void; logout: () => void }
const navigation = [['🏠', 'Início', '/'], ['📥', 'Raw Provider', '/raw'], ['🎨', 'Clean / Redraw', '/clean-redraw'], ['🌐', 'Tradução', '/translation'], ['✒️', 'Type', '/typeset'], ['🔎', 'Revisão / QC', '/review'], ['✅', 'Prontos', '/ready'], ['📚', 'Obras', '/works'], ['🔔', 'Notificações', '/notifications']]

export function PanelRoutes(props: PanelProps) { return <Routes><Route element={<Shell {...props} />}><Route index element={<HomePage {...props} />} /><Route path="raw" element={<StagePage {...props} stage="RAW" />} /><Route path="clean-redraw" element={<StagePage {...props} stage="CLEAN_REDRAW" />} /><Route path="translation" element={<StagePage {...props} stage="TRANSLATION" />} /><Route path="typeset" element={<StagePage {...props} stage="TYPESET" />} /><Route path="review" element={<StagePage {...props} stage="REVIEW" />} /><Route path="ready" element={<ReadyPage {...props} />} /><Route path="works" element={<WorksPage {...props} />} /><Route path="works/:id" element={<WorkPage {...props} />} /><Route path="chapters/:id" element={<ChapterPage {...props} />} /><Route path="notifications" element={<NotificationsPage {...props} />} />{props.member.is_admin && <><Route path="admin/members" element={<MembersPage {...props} />} /><Route path="admin/settings" element={<SettingsPage />} /></>}<Route path="*" element={<NotFound />} /></Route></Routes> }

function Shell({ member, notifications, toast, logout }: PanelProps) { const navigate = useNavigate(); return <div className="app"><aside><h1>Project Nox <small>Scan Staff</small></h1><nav>{navigation.map(([icon, label, to]) => <NavLink key={to} to={to}><span>{icon}</span>{label}</NavLink>)}{member.is_admin && <><p>ADMIN</p><NavLink to="/admin/members"><span>👥</span>Membros</NavLink><NavLink to="/admin/settings"><span>⚙️</span>Configurações</NavLink></>}</nav><div className="profile"><strong>{member.display_name || member.github_login}</strong><span>@{member.github_login} · {(member.roles ?? []).join(', ') || 'Staff'}</span><button onClick={logout}>Sair</button></div></aside><main><header><div><p className="eyebrow">PAINEL DE PRODUÇÃO</p><h2>Project Nox Scan</h2></div><button className="bell" onClick={() => navigate('/notifications')} aria-label="Abrir notificações">🔔{notifications ? <b>{notifications}</b> : null}</button></header>{toast ? <div className="toast" role="status">{toast}</div> : null}<Outlet /></main></div> }

function HomePage(props: PanelProps) { const mine = allStages(props.chapters).filter(({ stage }) => stage.assigned_to === props.member.user_id && stage.status === 'IN_PROGRESS'); const queue = allStages(props.chapters).filter(({ stage }) => stage.status === 'AVAILABLE' || stage.status === 'IN_PROGRESS'); return <section className="dashboard-grid"><Panel title="Minhas tarefas">{mine.length ? mine.map((x) => <TaskCard key={x.stage.id} {...x} {...props} />) : <Empty text="Nenhuma tarefa atribuída a você." />}</Panel><Panel title="Filas de produção">{queue.length ? queue.map((x) => <TaskCard key={x.stage.id} {...x} {...props} />) : <Empty text="Nenhum capítulo aguardando uma etapa." />}</Panel><Panel title="Capítulos em andamento">{props.chapters.length ? props.chapters.map((chapter) => <Link className="chapter" key={chapter.id} to={`/chapters/${chapter.id}`}><strong>{chapter.work?.title} #{chapter.number}</strong><span>{(chapter.chapter_stages ?? []).map((stage) => `${stageLabel[stage.stage]}: ${stage.status}`).join(' · ')}</span></Link>) : <Empty text="Nenhum capítulo em andamento." />}</Panel></section> }

function StagePage(props: PanelProps & { stage: Stage }) { const entries = allStages(props.chapters).filter((x) => x.stage.stage === props.stage); const available = entries.filter((x) => x.stage.status === 'AVAILABLE'); const active = entries.filter((x) => x.stage.status === 'IN_PROGRESS'); const done = entries.filter((x) => x.stage.status === 'COMPLETED').slice(0, 10); return <section className="page"><h2>{stageLabel[props.stage]}</h2><QueueGroup title="Disponíveis" entries={available} props={props} empty="Nenhuma tarefa disponível." /><QueueGroup title="Em andamento" entries={active} props={props} empty="Nenhuma tarefa em andamento." /><QueueGroup title="Concluídos recentes" entries={done} props={props} empty="Nenhuma conclusão recente." /></section> }
function QueueGroup({ title, entries, props, empty }: { title: string; entries: Entry[]; props: PanelProps; empty: string }) { return <section className="panel"><h3>{title}</h3>{entries.length ? entries.map((x) => <TaskCard key={x.stage.id} {...x} {...props} />) : <Empty text={empty} />}</section> }

function ReadyPage(props: PanelProps) { const ready = allStages(props.chapters).filter((x) => x.stage.stage === 'READY' && x.stage.status === 'COMPLETED'); return <section className="page"><h2>Prontos para publicação</h2><QueueGroup title="Capítulos aprovados" entries={ready} props={props} empty="Nenhum capítulo pronto para publicação." /></section> }

function TaskCard({ chapter, stage, member, refresh }: Entry & Pick<PanelProps, 'member' | 'refresh'>) { const [message, setMessage] = useState(''); const required = stage.stage === 'READY' ? 'ADMIN' : stageRole[stage.stage as keyof typeof stageRole]; const canClaim = stage.status === 'AVAILABLE' && (member.is_admin || member.roles.includes(required as Role)); const canRelease = stage.status === 'IN_PROGRESS' && (member.is_admin || stage.assigned_to === member.user_id); const action = async (name: 'claim' | 'release') => { try { if (name === 'claim') await claimStage(stage.id); else await releaseStage(stage.id); refresh() } catch (error) { setMessage(error instanceof Error ? error.message : 'Não foi possível atualizar a tarefa.') } }; return <article className="task"><Link to={`/chapters/${chapter.id}`}><strong>{chapter.work?.title} #{chapter.number}</strong></Link><span>{stageLabel[stage.stage]} · {stage.status}</span>{stage.assignee ? <span className="assignee">{stage.assignee.avatar_url ? <img src={stage.assignee.avatar_url} alt="" /> : '👤'} {stage.assignee.display_name || stage.assignee.github_login}</span> : null}{canClaim ? <button className="primary" onClick={() => void action('claim')}>Assumir tarefa</button> : null}{canRelease ? <button className="secondary" onClick={() => void action('release')}>Liberar tarefa</button> : null}{message ? <small className="error">{message}</small> : null}</article> }

function WorksPage({ member }: PanelProps) { const [works, setWorks] = useState<{ id: string; title: string; status: string }[]>([]); const [title, setTitle] = useState(''); const [error, setError] = useState(''); const load = () => void supabase?.from('works').select('id,title,status').order('title').then(({ data, error }) => { if (error) setError(error.message); else setWorks(data ?? []) }); useEffect(load, []); const create = async () => { if (!title.trim() || !supabase) return; const { error } = await supabase.from('works').insert({ title: title.trim() }); if (error) setError(error.message); else { setTitle(''); load() } }; return <section className="page"><h2>Obras</h2>{member.is_admin ? <section className="panel"><h3>Nova obra</h3><input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Título da obra" /><button className="primary" onClick={() => void create()}>Criar obra</button></section> : null}<section className="panel">{works.map((work) => <Link className="chapter" key={work.id} to={`/works/${work.id}`}><strong>{work.title}</strong><span>{work.status}</span></Link>)}{!works.length ? <Empty text={error || 'Nenhuma obra cadastrada.'} /> : null}</section></section> }

function WorkPage({ chapters }: PanelProps) { const { id } = useParams(); const entries = chapters.filter((chapter) => chapter.work?.id === id); return <section className="page"><h2>{entries[0]?.work?.title || 'Obra'}</h2><section className="panel"><h3>Capítulos</h3>{entries.length ? entries.map((chapter) => <Link className="chapter" to={`/chapters/${chapter.id}`} key={chapter.id}><strong>#{chapter.number}</strong><span>{(chapter.chapter_stages ?? []).map((stage) => `${stageLabel[stage.stage]}: ${stage.status}`).join(' · ')}</span></Link>) : <Empty text="Nenhum capítulo cadastrado nesta obra." />}</section></section> }

function ChapterPage(props: PanelProps) { const { id } = useParams(); const chapter = props.chapters.find((item) => item.id === id); const [comment, setComment] = useState(''); const [message, setMessage] = useState(''); if (!chapter) return <NotFound text="Capítulo não encontrado." />; const submitComment = async () => { try { await addComment(chapter.id, comment); setComment(''); props.refresh() } catch (error) { setMessage(error instanceof Error ? error.message : 'Não foi possível enviar comentário.') } }; return <section className="page"><h2>{chapter.work?.title} #{chapter.number}</h2><section className="panel"><h3>Workflow</h3>{(chapter.chapter_stages ?? []).map((stage) => <TaskCard key={stage.id} chapter={chapter} stage={stage} {...props} />)}</section><section className="panel"><h3>Comentários</h3><textarea value={comment} onChange={(event) => setComment(event.target.value)} placeholder="Adicionar comentário interno" /><button className="primary" disabled={!comment.trim()} onClick={() => void submitComment()}>Comentar</button>{message ? <small className="error">{message}</small> : null}</section><section className="panel"><h3>Arquivos e histórico</h3><Empty text="Arquivos e versões desta etapa aparecem aqui após os uploads." /></section></section> }

function NotificationsPage({ refresh }: PanelProps) { const [items, setItems] = useState<{ id: string; body: string; link_path: string | null; read_at: string | null; created_at: string }[]>([]); const navigate = useNavigate(); const load = () => void supabase?.from('notifications').select('id,body,link_path,read_at,created_at').order('read_at', { ascending: true }).order('created_at', { ascending: false }).then(({ data }) => setItems(data ?? [])); useEffect(load, []); const open = async (item: typeof items[number]) => { if (!item.read_at) await markNotificationRead(item.id); refresh(); load(); navigate(item.link_path || '/notifications') }; return <section className="page"><h2>Notificações</h2><button className="secondary" onClick={() => void markAllNotificationsRead().then(() => { refresh(); load() })}>Marcar todas como lidas</button><section className="panel">{items.map((item) => <button className={`notification ${item.read_at ? '' : 'unread'}`} key={item.id} onClick={() => void open(item)}>{item.body}<small>{new Date(item.created_at).toLocaleString('pt-BR')}</small></button>)}{!items.length ? <Empty text="Nenhuma notificação." /> : null}</section></section> }

function MembersPage() { const [members, setMembers] = useState<{ user_id: string; github_login: string; display_name: string | null; is_active: boolean; is_admin: boolean }[]>([]); const [login, setLogin] = useState(''); const [error, setError] = useState(''); const load = () => void supabase?.from('staff_members').select('user_id,github_login,display_name,is_active,is_admin').order('github_login').then(({ data, error }) => { if (error) setError(error.message); else setMembers(data ?? []) }); useEffect(load, []); const invite = async () => { if (!login.trim() || !supabase) return; const { error } = await supabase.from('staff_invites').insert({ github_login: login.trim(), roles: [] }); if (error) setError(error.message); else { setLogin(''); load() } }; const toggle = async (member: typeof members[number]) => { const { error } = await supabase!.from('staff_members').update({ is_active: !member.is_active }).eq('user_id', member.user_id); if (error) setError(error.message); else load() }; return <section className="page"><h2>Membros</h2><section className="panel"><h3>Pré-autorizar GitHub</h3><input value={login} onChange={(event) => setLogin(event.target.value)} placeholder="@github-login" /><button className="primary" onClick={() => void invite()}>Adicionar membro</button></section><section className="panel">{members.map((member) => <article className="task" key={member.user_id}><strong>{member.display_name || member.github_login}</strong><span>@{member.github_login} · {member.is_admin ? 'Administrador' : 'Staff'} · {member.is_active ? 'Ativo' : 'Desativado'}</span><button className="secondary" onClick={() => void toggle(member)}>{member.is_active ? 'Desativar' : 'Reativar'}</button></article>)}{error ? <small className="error">{error}</small> : null}</section></section> }
function SettingsPage() { return <section className="page"><h2>Configurações</h2><section className="panel"><h3>Projeto</h3><p>As permissões, OAuth, storage e workflow são administrados pelo Supabase e pelas migrations versionadas.</p></section></section> }
function Panel({ title, children }: { title: string; children: React.ReactNode }) { return <section className="panel"><h3>{title}</h3>{children}</section> }
function Empty({ text }: { text: string }) { return <p className="empty">{text}</p> }
function NotFound({ text = 'Página não encontrada.' }: { text?: string }) { return <section className="page"><h2>{text}</h2><Link className="primary" to="/">Voltar ao início</Link></section> }
type Entry = { chapter: Chapter; stage: ChapterStage }
const allStages = (chapters: Chapter[]): Entry[] => chapters.flatMap((chapter) => (chapter.chapter_stages ?? []).map((stage) => ({ chapter, stage })))
